version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: workdb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: gersonandre
      MYSQL_DATABASE: gandre
      MYSQL_USER: admin
      MYSQL_PASSWORD: gandre
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - gersonandre

volumes:
  mysql_data:

networks:
  gersonandre:
